spring:
  application:
    name: course-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/courseservice_db?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: Decembrie2001
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  jwt:
    secretKey: asdasdasdasdasd123344asdasdasdasdasasd12321332sadas
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 7

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8082

feign:
  client:
    config:
      default:
        loggerLevel: full
        
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

param:
  courses-auth-service: localhost