spring:

  datasource:
    url: jdbc:mysql://mysql:3306/courseservice_db?createDatabaseIfNotExist=true
    username: root
    password: root

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

param:
  courses-auth-service: courses-auth-service



